// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMS.EF.Models;

public partial class Application
{
    public long Id { get; set; }

    public long CustomerId { get; set; }

    public string Name { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Tool> Tools { get; set; } = new List<Tool>();
}