// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMS.EF.Models;

public partial class FieldType
{
    public long Id { get; set; }

    public string Type { get; set; }

    public virtual ICollection<ToolInput> ToolInputs { get; set; } = new List<ToolInput>();

    public virtual ICollection<ToolOutput> ToolOutputs { get; set; } = new List<ToolOutput>();
}