// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMS.EF.Models;

public partial class InputOption
{
    public long Id { get; set; }

    public long InputId { get; set; }

    public string Label { get; set; }

    public string Value { get; set; }

    public virtual ToolInput Input { get; set; }
}