// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMS.EF.Models;

public partial class ToolInput
{
    public long Id { get; set; }

    public long ToolId { get; set; }

    public long FieldTypeId { get; set; }

    public string Name { get; set; }

    public string Label { get; set; }

    public string Placeholder { get; set; }

    public virtual FieldType FieldType { get; set; }

    public virtual ICollection<InputOption> InputOptions { get; set; } = new List<InputOption>();

    public virtual Tool Tool { get; set; }
}