// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMS.EF.Models;

public partial class ToolOutput
{
    public long Id { get; set; }

    public long ToolId { get; set; }

    public long FieldTypeId { get; set; }

    public string Name { get; set; }

    public virtual FieldType FieldType { get; set; }

    public virtual Tool Tool { get; set; }
}